apriltag:
  ros__parameters:
    # Setup
    image_transport: "raw"
    family: "36h11"
    size: 0.127  
    
    # Pose Estimation
    pose_estimation_method: "pnp"
    publish_tf: true
    camera_frame: "camera_link"

    # Specific Tag Configuration
    tag:
      ids: [5]
      frames: ["36h11:5"]
      sizes: [0.127]

leader_detection:
  ros__parameters:
    leader_tag_id: 5
    tag_family: "36h11"